version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=water_monitoring_system.settings
    depends_on:
      - mysql
    expose:
      - 8001
    networks:
      - webnet
  
  mysql:
    image: mysql:8.0.34
    container_name: wtp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"  # avoid conflict with local MySQL
    volumes:
      - ./mysql-config/docker-bind.cnf:/etc/mysql/conf.d/docker-bind.cnf
      - mysql_data:/var/lib/mysql
    networks:
      - webnet
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - webnet

volumes:
  mysql_data:
    external: true
networks:
  webnet:
    driver: bridge
