version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=water_monitoring_system.settings
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"  # allows container to access your local MySQL

  mysql:
    image: mysql:8.0.34
    container_name: wtp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Bliss@Jarvis20
    ports:
      - "3308:3306"  # avoid conflict with local MySQL
    volumes:
      - ./mysql-config/docker-bind.cnf:/etc/mysql/conf.d/docker-bind.cnf
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    external: true
