# Generated by Django 5.1.7 on 2025-04-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0003_customuser_show_monthly_flow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterqualitydata',
            old_name='flow',
            new_name='flow1',
        ),
        migrations.AddField(
            model_name='waterqualitydata',
            name='flow2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterqualitydata',
            name='flow3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
