# Generated by Django 5.1.7 on 2025-04-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0002_customuser_show_bod_customuser_show_cod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_monthly_flow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waterqualitydata',
            name='monthly_flow',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
