# Generated by Django 5.1.7 on 2025-05-09 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0005_rename_show_daily_flow_customuser_show_daily_flow1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'machine',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_daily_flow1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_daily_flow2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_daily_flow3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_monthly_flow1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_monthly_flow2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_monthly_flow3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_total_flow1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_total_flow2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='show_total_flow3',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='daily_flow1',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='daily_flow2',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='daily_flow3',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='flow1',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='flow2',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='flow3',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='monthly_flow1',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='monthly_flow2',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='monthly_flow3',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='total_flow1',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='total_flow2',
        ),
        migrations.RemoveField(
            model_name='waterqualitydata',
            name='total_flow3',
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('value', models.FloatField(blank=True, default=None, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(db_column='machine_id', on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.machine')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading',
                'managed': True,
            },
        ),
    ]
