# Generated by Django 5.1.7 on 2025-05-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0007_customuser_show_flow10_customuser_show_flow4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowMeterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(default='/dev/ttyUSB0', max_length=50)),
                ('slave_id', models.PositiveIntegerField(default=1)),
                ('flow_register', models.PositiveIntegerField(default=2)),
                ('total_register', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['user', 'parameter', 'recorded_at'], name='reading_user_id_30e7da_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['machine', 'parameter', 'recorded_at'], name='reading_machine_cb99fe_idx'),
        ),
        migrations.AddField(
            model_name='flowmeterconfig',
            name='machine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring_app.machine'),
        ),
    ]
